Remove all mentions of `realpath` from docs
`realpath` is no longer needed to run executables.

diff --git a/tests/base/system_info001/run b/tests/base/system_info001/run
--- a/tests/base/system_info001/run
+++ b/tests/base/system_info001/run
@@ -3,7 +3,7 @@ rm -rf build
 rm -f expected
 
 if ! NProcs=$(nproc || sysctl -n hw.ncpu) 2>/dev/null; then
-  echo Command nproc not found. Try installing coreutils. >&2
+  echo "Command 'nproc' not found." >&2
   exit 1
 fi
 
